title: "Java Interview Fool"
description: "Материалы для подготовки"
baseurl: ""
url: "https://gitlobanov.github.io/interview-java-backend/"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
   posts:
     output: true
     permalink: /:path/

defaults:
  - scope:
      path: ""
    values:
      layout: "default"