title: "Java Interview Fool"
description: "Материалы для подготовки"
baseurl: ""
url: "https://gitlobanov.github.io/interview-java-backend/"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  inforage:
    output: true
    permalink: /inforage/:path/
  qa:
    output: true
    permalink: /qa/:path/

defaults:
  - scope:
      path: "_inforage"
      type: "inforage"
    values:
      layout: "default"
  - scope:
      path: "_qa"
      type: "qa"
    values:
      layout: "default"